# frozen_string_literal: true

tap 'github/gh'
tap 'heroku/brew'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'
tap 'twpayne/taps'

brew 'git'
brew 'graphviz'
brew 'icu4c'
brew 'openssl'
brew 'readline'
brew 'zlib'

brew 'asdf'
brew 'chezmoi'
brew 'gh'
brew 'heroku'
brew 'htop'
brew 'mysql'
brew 'nginx'
brew 'nodenv'
brew 'node-build', args: ['HEAD']
brew 'postgresql'
brew 'pyenv'
brew 'rbenv'
brew 'ruby-build', args: ['HEAD']
brew 'sqlite'
brew 'thefuck'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'

cask '1password'
cask '1password-cli'
cask 'dash'
cask 'docker'
cask 'firefox'
cask 'font-jetbrains-mono'
cask 'github'
cask 'google-chrome'
cask 'gpg-suite-no-mail'
cask 'iterm2'
cask 'ngrok'
cask 'notion'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'visual-studio-code'
