name: CI

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run rubocop
        run: bundle exec rubocop --parallel

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Install Node dependencies
        run: npm install

      - name: Run prettier
        run: npm run prettier:check
